# Generated by Django 4.2.2 on 2024-01-13 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TuneTracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='song_count',
            field=models.IntegerField(default=0),
        ),
    ]
